[package]
name = "rs-ngnix"
version = "0.1.0"
edition = "2024"


[dependencies]
tokio = { version = "1", features = ["full"] }
serde_yaml = "0.9"
serde = { version = "1.0.228", features = ["derive"] }
