http:
  - listen: 8080
    root: "D:/Github/rs-ngnix/"
    cache: 1024
  - listen: 8081
    proxy:
      - "127.0.0.1:3000"
      - "127.0.0.1:3002"
      - "127.0.0.1:3003"
      - "127.0.0.1:3004"
      - "127.0.0.1:3005"
    proxy_health: "/health"
    strategy: "weighted_round_robin"
    weights:
      - 1
      - 1
      - 5
      - 1
      - 1